2020-05-02 19:19:48,250 ERROR: Exception on /explore [GET] [in /Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/benliu/PycharmProjects/microblog/app/routes.py", line 156, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2020-05-02 19:20:54,076 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 19:22:07,917 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 19:22:48,207 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-06 11:56:46,212 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 12:04:29,698 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 12:19:54,724 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 12:20:23,423 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 12:35:20,019 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 12:35:22,171 ERROR: Exception on /index [GET] [in /Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/benliu/PycharmProjects/microblog/app/routes.py", line 44, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/_post.html", line 40, in top-level template code
    <a href="{{ url_for('like', post_id=post.id) }}">Like</a>
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'like' with values ['post_id']. Did you forget to specify values ['prev_url']?
2020-05-06 12:35:52,040 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
2020-05-06 13:52:00,920 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:55]
